name: 'SecureStack Code Analysis'
description: 'Execute SecureStack Code Analysis'
inputs:
  securestack_api_key:
    description: 'SecureStack API key - generate one at https://app.securestack.com'
    required: true
  securestack_app_id:
    description: 'SecureStack Application ID - available when viewing applications at https://app.securestack.com'
    required: true
  severity:
    description: 'Severities lower than this value will not be reported; value should be one of: critical | high | medium | low'
    required: true
  language:
    description: 'Language used for repository code; value should be one of: node | python | yarn'
    required: true
  package_metadata_path:
    description: 'Optional location for package metadata files'
    required: false
    default: './'
outputs:
  result:
    description: 'Code Analysis Result'
runs:
  using: 'docker'
  image: 'docker://securestackau/bloodhound-cli'
  env:
    BH_API_KEY: ${{ inputs.securestack_api_key }}
    BH_APP_ID: ${{ inputs.securestack_app_id }}
    BH_SEVERITY: ${{ inputs.severity }}
  args:
    - code
    - -t
    - ${{ inputs.language }}
    - -p
    - ${{ inputs.package_metadata_path }}
